/* -------------------------------------------------------------------------- */
/* ESTATÍSTICAS                                                                */
/* -------------------------------------------------------------------------- */
async function renderEstatisticas(){ const c=contextCeremony(); if(!c){$('#main').innerHTML='<div class="empty">Nenhuma cerimônia ativa.</div>';return;} const rows=await server('apiEstatisticas',c.ID_CERIMONIA); $('#main').innerHTML=`<div class="page-head"><div><div class="section-title">ESTATÍSTICAS POR CÍRCULO</div><div class="small muted">${esc(c.NOME_EVENTO)}</div></div><div class="page-actions single"><button class="btn outline" onclick="openStatsConfig()">CONFIGURAR CÍRCULOS</button></div></div><div class="stats-wrap"><table class="stats"><thead><tr><th>GRUPO</th><th>CONF.</th><th>PRES.</th><th>PEND.</th><th>NÃO VIRÁ</th><th>TOTAL</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.GRUPO)}</td><td>${r.CONFIRMADOS}</td><td><strong>${r.PRESENTES}</strong></td><td>${r.PENDENTES}</td><td>${r.NAO_COMPARECERA}</td><td><strong>${r.TOTAL}</strong></td></tr>`).join('')}</tbody></table></div>`; }
async function openStatsConfig(){ const c=contextCeremony(),[groups,opts]=await Promise.all([server('apiListarGruposEstatistica'),server('apiOpcoesEstatistica',c.ID_CERIMONIA)]); state.statsConfig={groups,opts}; openModal(`${modalCloseButton()}<h2>Configurar círculos estatísticos</h2><p class="small muted">Acrescente postos e autoridades específicas conforme surgirem. A classificação nominal prevalece sobre a automática.</p>${groups.filter(g=>g.tipo==='CONVIDADOS').map(g=>statsGroupHtml(g,opts)).join('')}`,true); }
function statsGroupHtml(g,opts){ return `<div class="circle-card"><div class="title">${esc(g.nome)}</div><div class="small muted">Postos cadastrados</div><div class="chips">${(g.postos||[]).map(p=>`<span class="chip">${esc(p)}<button onclick="removePostFromGroup('${g.id}','${esc(p)}')">X</button></span>`).join('')||'<span class="small muted">Nenhum posto específico.</span>'}</div><div class="row"><select id="posto_${g.id}" class="grow">${opts.postos.map(p=>`<option>${esc(p)}</option>`).join('')}</select><button class="btn outline sm" onclick="addPostToGroup('${g.id}')">ADICIONAR POSTO</button></div><div class="small muted" style="margin-top:10px">Autoridades específicas</div><div class="chips">${(g.autoridades||[]).map(id=>{const a=opts.autoridades.find(x=>x.ID_AUTORIDADE===id);return`<span class="chip">${esc(a?a.NOME:id)}<button onclick="removeAuthorityFromGroup('${g.id}','${id}')">X</button></span>`}).join('')||'<span class="small muted">Nenhuma autoridade específica.</span>'}</div><div class="row"><select id="aut_${g.id}" class="grow">${opts.autoridades.map(a=>`<option value="${a.ID_AUTORIDADE}">${esc(a.NOME)}</option>`).join('')}</select><button class="btn outline sm" onclick="addAuthorityToGroup('${g.id}')">ADICIONAR AUTORIDADE</button></div></div>`; }
async function addPostToGroup(id){ const p=$('#posto_'+id).value; if(p)await server('apiAdicionarPostoGrupo',id,p); openStatsConfig(); }
async function removePostFromGroup(id,p){ await server('apiRemoverPostoGrupo',id,p); openStatsConfig(); }
async function addAuthorityToGroup(id){ const a=$('#aut_'+id).value; if(a)await server('apiAdicionarAutoridadeGrupo',id,a); openStatsConfig(); }
async function removeAuthorityFromGroup(id,a){ await server('apiRemoverAutoridadeGrupo',id,a); openStatsConfig(); }

